/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportRouteImport } from './routes/report'
import { Route as MyRouteImport } from './routes/my'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsWithdrawRouteImport } from './routes/settings.withdraw'
import { Route as SettingsThemeRouteImport } from './routes/settings.theme'
import { Route as SettingsLanguageRouteImport } from './routes/settings.language'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWithdrawRoute = SettingsWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/withdraw': typeof SettingsWithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/withdraw': typeof SettingsWithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/withdraw': typeof SettingsWithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/my'
    | '/report'
    | '/settings'
    | '/settings/language'
    | '/settings/theme'
    | '/settings/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/my'
    | '/report'
    | '/settings'
    | '/settings/language'
    | '/settings/theme'
    | '/settings/withdraw'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/my'
    | '/report'
    | '/settings'
    | '/settings/language'
    | '/settings/theme'
    | '/settings/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MyRoute: typeof MyRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/withdraw': {
      id: '/settings/withdraw'
      path: '/withdraw'
      fullPath: '/settings/withdraw'
      preLoaderRoute: typeof SettingsWithdrawRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/language': {
      id: '/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof SettingsLanguageRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsLanguageRoute: typeof SettingsLanguageRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  SettingsWithdrawRoute: typeof SettingsWithdrawRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsLanguageRoute: SettingsLanguageRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  SettingsWithdrawRoute: SettingsWithdrawRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MyRoute: MyRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
