/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportRouteImport } from './routes/report'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as MyRouteImport } from './routes/my'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsTermsRouteImport } from './routes/settings.terms'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsNoticesRouteImport } from './routes/settings.notices'
import { Route as SettingsLanguageRouteImport } from './routes/settings.language'
import { Route as NoticesNoticeIdRouteImport } from './routes/notices.$noticeId'
import { Route as MyReportsRouteImport } from './routes/my.reports'
import { Route as MyFavoritesRouteImport } from './routes/my.favorites'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTermsRoute = SettingsTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNoticesRoute = SettingsNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => SettingsRoute,
} as any)
const NoticesNoticeIdRoute = NoticesNoticeIdRouteImport.update({
  id: '/$noticeId',
  path: '/$noticeId',
  getParentRoute: () => NoticesRoute,
} as any)
const MyReportsRoute = MyReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MyRoute,
} as any)
const MyFavoritesRoute = MyFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => MyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/notices': typeof NoticesRouteWithChildren
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/my/favorites': typeof MyFavoritesRoute
  '/my/reports': typeof MyReportsRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notices': typeof SettingsNoticesRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/terms': typeof SettingsTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/notices': typeof NoticesRouteWithChildren
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/my/favorites': typeof MyFavoritesRoute
  '/my/reports': typeof MyReportsRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notices': typeof SettingsNoticesRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/terms': typeof SettingsTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my': typeof MyRouteWithChildren
  '/notices': typeof NoticesRouteWithChildren
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/my/favorites': typeof MyFavoritesRoute
  '/my/reports': typeof MyReportsRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notices': typeof SettingsNoticesRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/terms': typeof SettingsTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/my'
    | '/notices'
    | '/report'
    | '/settings'
    | '/sitemap.xml'
    | '/my/favorites'
    | '/my/reports'
    | '/notices/$noticeId'
    | '/settings/language'
    | '/settings/notices'
    | '/settings/privacy'
    | '/settings/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/my'
    | '/notices'
    | '/report'
    | '/settings'
    | '/sitemap.xml'
    | '/my/favorites'
    | '/my/reports'
    | '/notices/$noticeId'
    | '/settings/language'
    | '/settings/notices'
    | '/settings/privacy'
    | '/settings/terms'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/my'
    | '/notices'
    | '/report'
    | '/settings'
    | '/sitemap.xml'
    | '/my/favorites'
    | '/my/reports'
    | '/notices/$noticeId'
    | '/settings/language'
    | '/settings/notices'
    | '/settings/privacy'
    | '/settings/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MyRoute: typeof MyRouteWithChildren
  NoticesRoute: typeof NoticesRouteWithChildren
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/terms': {
      id: '/settings/terms'
      path: '/terms'
      fullPath: '/settings/terms'
      preLoaderRoute: typeof SettingsTermsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notices': {
      id: '/settings/notices'
      path: '/notices'
      fullPath: '/settings/notices'
      preLoaderRoute: typeof SettingsNoticesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/language': {
      id: '/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof SettingsLanguageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/notices/$noticeId': {
      id: '/notices/$noticeId'
      path: '/$noticeId'
      fullPath: '/notices/$noticeId'
      preLoaderRoute: typeof NoticesNoticeIdRouteImport
      parentRoute: typeof NoticesRoute
    }
    '/my/reports': {
      id: '/my/reports'
      path: '/reports'
      fullPath: '/my/reports'
      preLoaderRoute: typeof MyReportsRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/favorites': {
      id: '/my/favorites'
      path: '/favorites'
      fullPath: '/my/favorites'
      preLoaderRoute: typeof MyFavoritesRouteImport
      parentRoute: typeof MyRoute
    }
  }
}

interface MyRouteChildren {
  MyFavoritesRoute: typeof MyFavoritesRoute
  MyReportsRoute: typeof MyReportsRoute
}

const MyRouteChildren: MyRouteChildren = {
  MyFavoritesRoute: MyFavoritesRoute,
  MyReportsRoute: MyReportsRoute,
}

const MyRouteWithChildren = MyRoute._addFileChildren(MyRouteChildren)

interface NoticesRouteChildren {
  NoticesNoticeIdRoute: typeof NoticesNoticeIdRoute
}

const NoticesRouteChildren: NoticesRouteChildren = {
  NoticesNoticeIdRoute: NoticesNoticeIdRoute,
}

const NoticesRouteWithChildren =
  NoticesRoute._addFileChildren(NoticesRouteChildren)

interface SettingsRouteChildren {
  SettingsLanguageRoute: typeof SettingsLanguageRoute
  SettingsNoticesRoute: typeof SettingsNoticesRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsTermsRoute: typeof SettingsTermsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsLanguageRoute: SettingsLanguageRoute,
  SettingsNoticesRoute: SettingsNoticesRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsTermsRoute: SettingsTermsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MyRoute: MyRouteWithChildren,
  NoticesRoute: NoticesRouteWithChildren,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
